### ISSUE TITLE
Not sure the sekere~ is working right

### ISSUE THREAD

**Issue by darwingrosse** [Cycling74/percolate#28]
Sounds like crap - or at least the same as the shaker~ stuff. Needs investigation.

**Comment by isabelgk** [comment]
Fixed with [a43fcfd49997fdcb4988dbf03a7b6844004ceda1](https://github.com/Cycling74/percolate/commit/a43fcfd49997fdcb4988dbf03a7b6844004ceda1#diff-41cf6794ba4200b839c53531555f0f3998df4cbb01a4d5cb0b94e3ca5e23947d)
