### ISSUE TITLE
inlets to munger~ mislabeled

### ISSUE THREAD

**Issue by sonoptik** [Cycling74/percolate#31]
The inlets to munger~ all need to move right one inlet. i.e the last inlet has nothing mentioned when it should be stereo spread, the second last inlet says stereo spread when it is in fact grain pitch variation.

<img width="369" alt="screen shot 2016-01-07 at 1 31 49 pm" src="https://cloud.githubusercontent.com/assets/11561131/12183316/0ac1c426-b543-11e5-8752-e6d94e93c9db.png">
<img width="342" alt="screen shot 2016-01-07 at 1 31 44 pm" src="https://cloud.githubusercontent.com/assets/11561131/12183317/0ada6d0a-b543-11e5-8cf0-969505baded7.png">

**Comment by mzed** [comment]
I just noticed the same problem.

**Comment by isabelgk** [comment]
This appears fixed.
