### ISSUE TITLE
Profiteering

### ISSUE THREAD

**Issue by CaligulaCuddles** [Cycling74/percolate#34]
If anyone cares, it looks like the blotar~ is literally the only thing generating audio in this commercial product: http://www.audiobulb.com/create/Lissajous/Lissajous.htm
Someone's cashing in.

**Comment by pukunui** [comment]
Thank you for thinking of this and letting us know

I found this.

"According to Alexa Traffic Rank audiobulb.com is ranked number 0 in the world."
