### ISSUE TITLE
Merge of munger1~ external into munger~

### ISSUE THREAD

**Issue by pd-l2ork** [Cycling74/percolate#36]
Here's a merge of features and fixes present in munger1~ external which was until recently a flext-only external. Also, attached is the updated help file.
[munger~1.3.2.zip](https://github.com/Cycling74/percolate/files/3369932/munger.1.3.2.zip)

**Comment by tap** [comment]
Thanks, Ivica! 

BTW, August mentioned that you have been in Boulder recently? If you are still around then we should get together!

**Comment by pd-l2ork** [comment]
Great to hear from you, Timothy. I am still in town. I did not know you are
located here, as well. It would be great to connect. Please contact me
offline and suggest a few times in the coming days--my schedule is fairly
flexible. Looking forward to it!

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
ico@vt.edu

www.icat.vt.edu
www.performingarts.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net
