### ISSUE TITLE
munger~ [postion] message selects as attrui

### ISSUE THREAD

**Issue by ashleybellouinc74** [Cycling74/percolate#37]
When you select ‘position’ from the object action menu, under messages, it instantiates as an attribute.

**Comment by isabelgk** [comment]
Possible fix will be to change the `name` parameter in `class_addmethod` from `"position"` to some other string. 

```
class_addmethod(c, (method)munger_setposition, "foo_position", A_GIMME, 0);
```

![image](https://user-images.githubusercontent.com/13615209/101941229-4f416980-3bad-11eb-90ae-7d25d38951c7.png)

**Comment by isabelgk** [comment]
Since this is an issue with the UI and not behavior, to avoid breaking old patches it would make more sense to not fix this for now. Perhaps this is something to change on the Max side?

**Comment by ashleybellouinc74** [comment]
Thanks for looking into this! We'll log a bug report on the Max side, since I think you're right that there's not really anything to fix here.
